---
# Reusable workflow to build the Hot Potato nuget package and archive the artifacts.
name: Build Hot Potato

on:
  workflow_call:
    outputs:
      version:
        description: Derived Hot Potato version
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
      major-minor-patch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Generate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: './GitVersion.yml'

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 6.0.x

  build:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
    - name: Build
      run: |
        dotnet build --configuration Release -p:Version=${{ needs.version.outputs.major-minor-patch }}

  unit-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Test
      env:
        SpecToken: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet test -c Release -s ./test/ci.runsettings --no-restore --no-build

  package:
    runs-on: ubuntu-latest
    needs: [version, build, unit-test]
    steps:
    - name: Package
      if: ${{ success() }}
      run: |
        dotnet pack -p:PackageVersion=${{ needs.version.outputs.version }} -c Release --no-build --no-restore --output ./nuget

  generate-sbom:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Generate sbom
      uses: anchore/sbom-action@v0.14.3
      with:
        path: ./

  archive-artifacts:
    runs-on: ubuntu-latest
    needs: [unit-test,package]
    steps:
    - name: Archive nuget package artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: nuget-packages
        path: ./nuget/**/*.nupkg

    - name: Archive test results
      uses: actions/upload-artifact@v3.1.2
      with:
        name: test-results
        path: ./test/results/*
